const boardData = [
  { col: '1', row: '8', lDiag: '8', rDiag: '1', active: false },
  { col: '2', row: '8', lDiag: '9', rDiag: '2', active: false },
  { col: '3', row: '8', lDiag: '10', rDiag: '3', active: false },
  { col: '4', row: '8', lDiag: '11', rDiag: '4', active: false },
  { col: '5', row: '8', lDiag: '12', rDiag: '5', active: false },
  { col: '6', row: '8', lDiag: '13', rDiag: '6', active: false },
  { col: '7', row: '8', lDiag: '14', rDiag: '7', active: false },
  { col: '8', row: '8', lDiag: '15', rDiag: '8', active: false },

  { col: '1', row: '7', lDiag: '7', rDiag: '2', active: false },
  { col: '2', row: '7', lDiag: '8', rDiag: '3', active: false },
  { col: '3', row: '7', lDiag: '9', rDiag: '4', active: false },
  { col: '4', row: '7', lDiag: '10', rDiag: '5', active: false },
  { col: '5', row: '7', lDiag: '11', rDiag: '6', active: false },
  { col: '6', row: '7', lDiag: '12', rDiag: '7', active: false },
  { col: '7', row: '7', lDiag: '13', rDiag: '8', active: false },
  { col: '8', row: '7', lDiag: '14', rDiag: '9', active: false },

  { col: '1', row: '6', lDiag: '6', rDiag: '3', active: false },
  { col: '2', row: '6', lDiag: '7', rDiag: '4', active: false },
  { col: '3', row: '6', lDiag: '8', rDiag: '5', active: false },
  { col: '4', row: '6', lDiag: '9', rDiag: '6', active: false },
  { col: '5', row: '6', lDiag: '10', rDiag: '7', active: false },
  { col: '6', row: '6', lDiag: '11', rDiag: '8', active: false },
  { col: '7', row: '6', lDiag: '12', rDiag: '9', active: false },
  { col: '8', row: '6', lDiag: '13', rDiag: '10', active: false },

  { col: '1', row: '5', lDiag: '5', rDiag: '4', active: false },
  { col: '2', row: '5', lDiag: '6', rDiag: '5', active: false },
  { col: '3', row: '5', lDiag: '7', rDiag: '6', active: false },
  { col: '4', row: '5', lDiag: '8', rDiag: '7', active: false },
  { col: '5', row: '5', lDiag: '9', rDiag: '8', active: false },
  { col: '6', row: '5', lDiag: '10', rDiag: '9', active: false },
  { col: '7', row: '5', lDiag: '11', rDiag: '10', active: false },
  { col: '8', row: '5', lDiag: '12', rDiag: '11', active: false },

  { col: '1', row: '4', lDiag: '4', rDiag: '5', active: false },
  { col: '2', row: '4', lDiag: '5', rDiag: '6', active: false },
  { col: '3', row: '4', lDiag: '6', rDiag: '7', active: false },
  { col: '4', row: '4', lDiag: '7', rDiag: '8', active: false },
  { col: '5', row: '4', lDiag: '8', rDiag: '9', active: false },
  { col: '6', row: '4', lDiag: '9', rDiag: '10', active: false },
  { col: '7', row: '4', lDiag: '10', rDiag: '11', active: false },
  { col: '8', row: '4', lDiag: '11', rDiag: '12', active: false },

  { col: '1', row: '3', lDiag: '3', rDiag: '6', active: false },
  { col: '2', row: '3', lDiag: '4', rDiag: '7', active: false },
  { col: '3', row: '3', lDiag: '5', rDiag: '8', active: false },
  { col: '4', row: '3', lDiag: '6', rDiag: '9', active: false },
  { col: '5', row: '3', lDiag: '7', rDiag: '10', active: false },
  { col: '6', row: '3', lDiag: '8', rDiag: '11', active: false },
  { col: '7', row: '3', lDiag: '9', rDiag: '12', active: false },
  { col: '8', row: '3', lDiag: '10', rDiag: '13', active: false },

  { col: '1', row: '2', lDiag: '2', rDiag: '7', active: false },
  { col: '2', row: '2', lDiag: '3', rDiag: '8', active: false },
  { col: '3', row: '2', lDiag: '4', rDiag: '9', active: false },
  { col: '4', row: '2', lDiag: '5', rDiag: '10', active: false },
  { col: '5', row: '2', lDiag: '6', rDiag: '11', active: false },
  { col: '6', row: '2', lDiag: '7', rDiag: '12', active: false },
  { col: '7', row: '2', lDiag: '8', rDiag: '13', active: false },
  { col: '8', row: '2', lDiag: '9', rDiag: '14', active: false },

  { col: '1', row: '1', lDiag: '1', rDiag: '8', active: false },
  { col: '2', row: '1', lDiag: '2', rDiag: '9', active: false },
  { col: '3', row: '1', lDiag: '3', rDiag: '10', active: false },
  { col: '4', row: '1', lDiag: '4', rDiag: '11', active: false },
  { col: '5', row: '1', lDiag: '5', rDiag: '12', active: false },
  { col: '6', row: '1', lDiag: '6', rDiag: '13', active: false },
  { col: '7', row: '1', lDiag: '7', rDiag: '14', active: false },
  { col: '8', row: '1', lDiag: '8', rDiag: '15', active: false },
];

export default boardData;
