const boardData = [
  { col: '1', row: '8', lDiag: '8', rDag: '1', active: false },
  { col: '2', row: '8', lDiag: '9', rDag: '2', active: false },
  { col: '3', row: '8', lDiag: '10', rDag: '3', active: false },
  { col: '4', row: '8', lDiag: '11', rDag: '4', active: false },
  { col: '5', row: '8', lDiag: '12', rDag: '5', active: false },
  { col: '6', row: '8', lDiag: '13', rDag: '6', active: false },
  { col: '7', row: '8', lDiag: '14', rDag: '7', active: false },
  { col: '8', row: '8', lDiag: '15', rDag: '8', active: false },

  { col: '1', row: '7', lDiag: '7', rDag: '2', active: false },
  { col: '2', row: '7', lDiag: '8', rDag: '3', active: false },
  { col: '3', row: '7', lDiag: '9', rDag: '4', active: false },
  { col: '4', row: '7', lDiag: '10', rDag: '5', active: false },
  { col: '5', row: '7', lDiag: '11', rDag: '6', active: false },
  { col: '6', row: '7', lDiag: '12', rDag: '7', active: false },
  { col: '7', row: '7', lDiag: '13', rDag: '8', active: false },
  { col: '8', row: '7', lDiag: '14', rDag: '9', active: false },

  { col: '1', row: '6', lDiag: '6', rDag: '3', active: false },
  { col: '2', row: '6', lDiag: '7', rDag: '4', active: false },
  { col: '3', row: '6', lDiag: '8', rDag: '5', active: false },
  { col: '4', row: '6', lDiag: '9', rDag: '6', active: false },
  { col: '5', row: '6', lDiag: '10', rDag: '7', active: false },
  { col: '6', row: '6', lDiag: '11', rDag: '8', active: false },
  { col: '7', row: '6', lDiag: '12', rDag: '9', active: false },
  { col: '8', row: '6', lDiag: '13', rDag: '10', active: false },

  { col: '1', row: '5', lDiag: '5', rDag: '4', active: false },
  { col: '2', row: '5', lDiag: '6', rDag: '5', active: false },
  { col: '3', row: '5', lDiag: '7', rDag: '6', active: false },
  { col: '4', row: '5', lDiag: '8', rDag: '7', active: false },
  { col: '5', row: '5', lDiag: '9', rDag: '8', active: false },
  { col: '6', row: '5', lDiag: '10', rDag: '9', active: false },
  { col: '7', row: '5', lDiag: '11', rDag: '10', active: false },
  { col: '8', row: '5', lDiag: '12', rDag: '11', active: false },

  { col: '1', row: '4', lDiag: '4', rDag: '5', active: false },
  { col: '2', row: '4', lDiag: '5', rDag: '6', active: false },
  { col: '3', row: '4', lDiag: '6', rDag: '7', active: false },
  { col: '4', row: '4', lDiag: '7', rDag: '8', active: false },
  { col: '5', row: '4', lDiag: '8', rDag: '9', active: false },
  { col: '6', row: '4', lDiag: '9', rDag: '10', active: false },
  { col: '7', row: '4', lDiag: '10', rDag: '11', active: false },
  { col: '8', row: '4', lDiag: '11', rDag: '12', active: false },

  { col: '1', row: '3', lDiag: '3', rDag: '6', active: false },
  { col: '2', row: '3', lDiag: '4', rDag: '7', active: false },
  { col: '3', row: '3', lDiag: '5', rDag: '8', active: false },
  { col: '4', row: '3', lDiag: '6', rDag: '9', active: false },
  { col: '5', row: '3', lDiag: '7', rDag: '10', active: false },
  { col: '6', row: '3', lDiag: '8', rDag: '11', active: false },
  { col: '7', row: '3', lDiag: '9', rDag: '12', active: false },
  { col: '8', row: '3', lDiag: '10', rDag: '13', active: false },

  { col: '1', row: '2', lDiag: '2', rDag: '7', active: false },
  { col: '2', row: '2', lDiag: '3', rDag: '8', active: false },
  { col: '3', row: '2', lDiag: '4', rDag: '9', active: false },
  { col: '4', row: '2', lDiag: '5', rDag: '10', active: false },
  { col: '5', row: '2', lDiag: '6', rDag: '11', active: false },
  { col: '6', row: '2', lDiag: '7', rDag: '12', active: false },
  { col: '7', row: '2', lDiag: '8', rDag: '13', active: false },
  { col: '8', row: '2', lDiag: '9', rDag: '14', active: false },

  { col: '1', row: '1', lDiag: '1', rDag: '8', active: false },
  { col: '2', row: '1', lDiag: '2', rDag: '9', active: false },
  { col: '3', row: '1', lDiag: '3', rDag: '10', active: false },
  { col: '4', row: '1', lDiag: '4', rDag: '11', active: false },
  { col: '5', row: '1', lDiag: '5', rDag: '12', active: false },
  { col: '6', row: '1', lDiag: '6', rDag: '13', active: false },
  { col: '7', row: '1', lDiag: '7', rDag: '14', active: false },
  { col: '8', row: '1', lDiag: '8', rDag: '15', active: false },
];

export default boardData;
